import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure` — see README.

import 'services/auth_service.dart';
import 'services/progress_service.dart';
import 'screens/splash_screen.dart';
import 'screens/auth/login_screen.dart';
import 'screens/auth/signup_screen.dart';
import 'screens/home_screen.dart';
import 'screens/about_screen.dart';
import 'screens/contact_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // --- Firebase setup (v2 upgrade path) ---------------------------------
  // v1 ships with a simple on-device account system (see auth_service.dart)
  // so the app works with zero backend setup. To switch to real Firebase
  // Auth + Google Sign-In later: run `flutterfire configure`, uncomment the
  // line below, and swap AuthService's internals. See README.md.
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const ScreenReaderAcademyApp());
}

class ScreenReaderAcademyApp extends StatelessWidget {
  const ScreenReaderAcademyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()..restoreSession()),
        ChangeNotifierProvider(create: (_) => ProgressService()..load()),
      ],
      child: MaterialApp(
        title: 'Screen Reader Academy',
        debugShowCheckedModeBanner: false,
        // A high-contrast, large-touch-target theme benefits low-vision
        // users as well as screen reader users navigating visually.
        theme: ThemeData(
          useMaterial3: true,
          colorSchemeSeed: const Color(0xFF1D4ED8), // accessible blue
          brightness: Brightness.light,
          visualDensity: VisualDensity.standard,
          textTheme: const TextTheme(
            bodyLarge: TextStyle(fontSize: 18),
            bodyMedium: TextStyle(fontSize: 16),
          ),
          elevatedButtonTheme: ElevatedButtonThemeData(
            style: ElevatedButton.styleFrom(
              minimumSize: const Size(88, 48), // meets 48dp touch target
              textStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
            ),
          ),
          appBarTheme: const AppBarTheme(centerTitle: false),
        ),
        darkTheme: ThemeData(
          useMaterial3: true,
          colorSchemeSeed: const Color(0xFF60A5FA),
          brightness: Brightness.dark,
        ),
        initialRoute: '/',
        routes: {
          '/': (_) => const SplashScreen(),
          '/login': (_) => const LoginScreen(),
          '/signup': (_) => const SignupScreen(),
          '/home': (_) => const HomeScreen(),
          '/about': (_) => const AboutScreen(),
          '/contact': (_) => const ContactScreen(),
        },
      ),
    );
  }
}
